"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import Compliance, ComplianceCreate, ComplianceUpdate
from .store import store

app = FastAPI(
    title="Equipment Calibration Compliance API",
    version="0.1.0",
    description="REST API for Equipment Calibration Compliance. Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "compliances", "description": "Compliances managed by this service."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/compliances", response_model=List[Compliance], tags=["compliances"])
def list_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/compliances", response_model=Compliance, status_code=201, tags=["compliances"])
def create_item(body: ComplianceCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/compliances/{item_id}", response_model=Compliance, tags=["compliances"])
def get_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Compliance not found")
    return item


@app.patch("/api/compliances/{item_id}", response_model=Compliance, tags=["compliances"])
def update_item(item_id: int, body: ComplianceUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="Compliance not found")
    return item


@app.delete("/api/compliances/{item_id}", status_code=204, tags=["compliances"])
def delete_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="Compliance not found")
